"""add energy burn and user profile

Revision ID: 88ac99f98349
Revises: 005
Create Date: 2025-09-25 13:16:48.115935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ac99f98349'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_burn_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('activity_name', sa.String(length=200), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('daily_calorie_goal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_constraint(op.f('calorie_entry_ibfk_1'), 'calorie_entry', type_='foreignkey')
    op.create_foreign_key(None, 'calorie_entry', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('exercise_log_ibfk_1'), 'exercise_log', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_log', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('food_log_ibfk_1'), 'food_log', type_='foreignkey')
    op.create_foreign_key(None, 'food_log', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_log', type_='foreignkey')
    op.create_foreign_key(op.f('food_log_ibfk_1'), 'food_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'exercise_log', type_='foreignkey')
    op.create_foreign_key(op.f('exercise_log_ibfk_1'), 'exercise_log', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'calorie_entry', type_='foreignkey')
    op.create_foreign_key(op.f('calorie_entry_ibfk_1'), 'calorie_entry', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('user_profile')
    op.drop_table('energy_burn_entry')
    # ### end Alembic commands ###